import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/lib/languageContext";
import { RadioPlayerProvider } from "@/components/radio/RadioPlayerContext";
import GlobalPlayerBar from "@/components/radio/GlobalPlayerBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai One | PRO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          {/* Mounted at the true app-shell level, above every route, so the
              <audio> element (and playback/volume/queue state) survives
              navigating between the SPA and standalone pages like
              /products — previously scoped inside app/page.tsx, so it
              unmounted entirely on any real route change. GlobalPlayerBar
              itself is fixed-positioned (see that component) precisely
              because every route below has its own independent layout. */}
          <RadioPlayerProvider>
            {children}
            <GlobalPlayerBar />
          </RadioPlayerProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
