import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/lib/languageContext";
import { RadioPlayerProvider } from "@/components/radio/RadioPlayerContext";
import GlobalPlayerBar from "@/components/radio/GlobalPlayerBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai One | PRO",
  description: "Generated by create next app",
};

// viewportFit: 'cover' — without this, env(safe-area-inset-bottom)
// always evaluates to 0 (no way for the page to know about the iOS
// home-indicator area at all), silently no-opping the safe-area padding
// just added to AiOneChat's sticky prompt bar.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          {/* Mounted at the true app-shell level, above every route, so the
              <audio> element (and playback/volume/queue state) survives
              navigating between the SPA and standalone pages like
              /products — previously scoped inside app/page.tsx, so it
              unmounted entirely on any real route change. GlobalPlayerBar
              itself is fixed-positioned (see that component) precisely
              because every route below has its own independent layout. */}
          <RadioPlayerProvider>
            {children}
            <GlobalPlayerBar />
          </RadioPlayerProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
